name: Guido Neele
favicon: null
layout_spectrum: 0.7484990356024355
typography_spectrum: 0.285253319889307
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5417987373657525
  lightness: 0.2780631168279797
  saturation: 0.15813306788913906
  rhythmicContrast: 0.5291242427192628
purpose: []
