name: Guido Neele
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22384
title: Persoonlijk blog van Guido Neele
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-352207-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
